apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: dev-eu-central-1
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
